language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - development
notifications:
  hipchat:
    rooms:
      secure: QDJPN/YH3ksShOijz/lmmjz+mp/A+A+V2tX3tCr6HLsmisGTGhP9HTRNdc3fSEaG2T/Ll8e9UQ0sU9sApHlEyo3tr18dxNWher3Oh9ub5dHBwkUXC2zSPPHkk/mdL6u78p12D9sGES71bmOuBEM/u1UleCgXVLjuTV2iWgv4QDvcufSOeGdsCWgGrLyRNCeNKZtffN2NQmXoaGE/Z3jOsmnKBD/2V0/Pi/0vJbMuv3L1c80PgTrG8mlQwrsMNLqUUK4psyEkWpS72PAZvsv6GwdQw3bPzkG/U76WpuBDmxcm0qgDDZWvYpoq9xq1CVl1JdytUVtcJN+i8RDDJEZRuAo/hDP5GmrE0XFChfnDIYxd20D4W3kwOvgV0bfZXbr0cU8HRS/IQKig6HNUWEd7VOoCh51PVLBCvVzdHVW5ehDzhlKM6BjrsMkQC6Tfg+MQ9jvp4WRJgn4Xc1mnQxVrMiuKUwxAlG1/Vkh6fAVfmDuEP5eZ0OL0LoJOGBFGyH1cxsW1Rilx2J0WtU8qDaGzVnY5hofO8e8V6XyUHqO/66BbKwLYyNnQ6E200EaMy09bTJQLH9sDcAkvhGG1w9Iwh+yVJonc2ilHwiMo1OcDYTKEYeksRsfqGjWxWcaGgVNQj0yWN8Z3Sz60hh6uqc05FvvNuIKBf3da5W+IdyddIGE=
    on_success: always
    on_failure: always
  webhooks:
    - https://udl-eps-softarch-softarch-1516.getbadges.io/api/app/webhook/8351ac66-5b54-4c6d-a38e-360c43c913fc
deploy:
  provider: heroku
  app:
    master: mydoodle
    development: mydoodle-test
  api_key:
    secure: WYC0gGf6AgYhc6EWsDgqjcG37hOIvpuegzUxhEquKr0cKlqjcwwendHCkszzp4cHo/cW553I9ju6UiSnm/ekg5sAumS1Ah91vomtezzCH/PI0j8GmevmRavwlyghlyw52x3cRkROSoDxtObBnVLYRaDL38v7pQkgitNC/rFI5R5jJfFSA5p0L6JQP9upttMZkvr4ui7CEiEqfefdB5KWVb9xlkmDH7aTXYx9eY+2Ky/XIwIudE9XeYtz7swsx6oY+rsK6hhZKlqcL3EV4Bvz9BwLLAR3fgecORQPj7G4la040MTFHUkOZjhCDn32X/2kMIf7iWeQkc/AwjKIQP0rsyxOl6foXsLYvlzNrf1p+oqIqOsoORHy8rhFZrU0qLN06Y8JIMgjyhRnBOd3xhIqymeAxsnjZH3/+Q+TBSi3XMF+ykLcv6oaUmCuag4kG4bhJ2fpFdOvk49Zl/aNwEp6FhvxDrBN0vlW5JByustLYsj8S6uSB3Bm3HGX+Tgrfj8mquzS3ywCnEI3ts3NKjNZVtgKj47DGVwpXqq0WVy2FZCTTLRR6N2rSuo2JVmTNj71vCXTS6adU0VUGA5ZpRwo0rTHfuwzk0l3aSkg9ZgJLfVR/hAIh+MYAZw9el32zBIc4KHflHf+j8bjb1Lp/3nut9o3Rw2lH+G/JXOGUwdRaAM=
